export type TCompanyAddress = {
  streetAddress: string;
  streetAddress2: string;
  streetAddress3: string;
  streetAddress4: string;
  addressType: string;
  locality: string;
  district: string;
  city: string;
  state: string;
  country: string;
  postalCode: string;
  officeType: string;
  activeStatus?: string;
  establishmentDate?: string;
};

export type TDirectorRole = {
  userName: string;
  companyId: string;
  middleName: string;
  firstName: string;
  cessationDate: string;
  educationalQualification: string;
  birthPlace: string;
  drivingLicenseNumber: string;
  mobileNumber: string;
  directorDeathDate: string;
  fathersFirstName: string;
  membershipNumber: string;
  roleLICValue: string;
  contributionForm: string;
  bodyCorpOutsideIndiaName: string;
  profitSharingPercentage: string;
  nationality: string;
  gender: string;
  roleEffectiveDate: string;
  occupationType: string;
  bodyCorporateType: string;
  din: string;
  isDisqualified: string;
  ucin: string;
  role: string;
  bodyCorpInsideIndiaName: string;
  kmpFlag: string;
  othersEducationalQualification: string;
  companyName: string;
  cin: string;
  opcFlag: string;
  fathersLastName: string;
  dob: string;
  approverId: string;
  fathersMiddleName: string;
  pan: string;
  monetaryContributionValue: string;
  oidFlag: string;
  authorizationStatus: string;
  passportNumber: string;
  residentOfIndia: string;
  userId: string;
  directorFlag: string;
  emailAddress: string;
  shareholdingPercentage: string;
  personType: string;
  areaOfOccupation: string;
  lastName: string;
  citizenOfIndia: string;
  occupation: string;
  opcType: string;
  otherOccupation: string;
  designation: string;
  signatoryAssociationStatus: string;
  currentDesignationDate: string;
};

export type TCompanyData = {
  CIN: string;
  company: string;
  companyType: string;
  companyOrigin: string;
  registrationNumber: string;
  dateOfIncorporation: string;
  emailAddress: string;
  whetherListedOrNot: string;
  companyCategory: string;
  companySubcategory: string;
  classOfCompany: string;
  authorisedCapital: string;
  paidUpCapital: string;
  numberOfMembers: string;
  dateOfLastAGM: string;
  strikeOff_amalgamated_transferredDate: string;
  llpStatus: string;
  statusUnderCIRP: string;
  numberOfPartners: string;
  numberOfDesignatedPartners: string;
  previousFirm_companyDetails: string;
  totalObligationOfContribution: string;
  mainDivision: string;
  mainDivisionDescription: string;
  statementDate: string;
  BSDefaulter2Yrs: string;
  BSDefaulter3Yrs: string;
  ARDefaulter2Yrs: string;
  ARDefaulter3Yrs: string;
  suspendedAtStockExchange: string;
  MCAMDSCompanyAddress: TCompanyAddress[];
  rocName: string;
  shareCapitalFlag: string;
  maximumNumberOfMembers: string;
  subscribedCapital: string;
  rdName: string;
  rdRegion: string;
  balanceSheetDate: string;
  inc22Aflag: string;
};

export type TDirectorData = {
  DIN: string;
  PAN: string;
  dateOfAppointment: string;
  DirectorDisqualified: string;
  FirstName: string;
  MiddleName: string;
  LastName: string;
  MCAUserRole: TDirectorRole[];
  contactAddress: TCompanyAddress[];
};

export type TMasterData = {
  companyData: TCompanyData;
  directorData: TDirectorData[];
};

export type TCompany = {
  _id: {
    $oid: string;
  };
  masterData: TMasterData;
  md_data: boolean;
};
